name: Example Teleport Workflow on d34af466-3330-400a-8490-ea04125f40e2-1

on:
  push:
    branches:
      - main

jobs:
  demo:
    permissions:
      # The "id-token: write" permission is required or Machine ID will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    # if you added a workflow name in the previous step, make sure you use the same value here
    name: javascript-amazon-project-bot-example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 16.0.4
      # server access example
      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v2
        with:
          proxy: tpaaa-staging.bitnimbus.io:443
          token: javascript-amazon-project-bot
          # Enable the submission of anonymous usage telemetry. This
          # helps us shape the future development of `tbot`. You can disable this
          # by omitting this.
          # anonymous-telemetry: 1
      - name: List nodes (tsh)
        # Enters a command from the cluster, in this case "tsh ls" using Machine
        # ID credentials to list remote SSH nodes.
        run: tsh ls
      - name: List nodes (tctl)
        run: tctl nodes ls
      - name: Run hostname via SSH (tsh)
        run: tsh ssh root@d34af466-3330-400a-8490-ea04125f40e2-1 hostname