name: Example Teleport Workflow on d34af466-3330-400a-8490-ea04125f40e2-1

on:
  push:
    branches:
      - main

jobs:
  demo:
    permissions:
      id-token: write
      contents: read
    environment: staging
    # if you added a workflow name in the previous step, make sure you use the same value here
    name: javascript-amazon-project-bot-example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule foreach git config --local url.https://github.com/.insteadOf git://github.com/
          git submodule foreach git config --local url.https://github.com/.insteadOf https://github.com/
        env:
          PAT: ${{ secrets.PAT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/javascript-amazon-site:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/javascript-amazon-site:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 16.0.4

      # server access example
      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v2
        with:
          proxy: tpaaa-staging.bitnimbus.io:443
          token: javascript-amazon-project-bot

      - name: List nodes (tsh)
        run: tsh ls

      - name: List nodes (tctl)
        run: tctl nodes ls

      - name: Run hostname via SSH (tsh)
        run: tsh ssh root@d34af466-3330-400a-8490-ea04125f40e2-1 hostname

      - name: Deploy updated Docker container
        run: |
         tsh ssh root@d34af466-3330-400a-8490-ea04125f40e2-1 << 'EOF'
          CONTAINER_NAME=$(docker ps --format '{{.Names}}')
          docker stop $CONTAINER_NAME
          docker system prune -a -f
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull ${{ secrets.DOCKER_USERNAME }}/javascript-amazon-site:latest
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/javascript-amazon-site:latest
         EOF